modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/GenerationsMod"
license = "Insert License Here"

[[mods]]
modId = "generations_music"
version = "${version}"
displayName = "Generations Music"
authors = "The Generations Team"
description = '''
'''
#logoFile = ""

[[dependencies.generations_music]]
modId = "forge"
mandatory = true
versionRange = "[47.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.generations_music]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"